export const UPDATE = 'UPDATE';
export const CALCULATE_MAGNETISATION = 'CALCULATE_MAGNETISATION';
export const CALCULATE_PROFILE = 'CALCULATE_PROFILE';
export const SIMULATE = 'SIMULATE';
export const CLEAR = 'CLEAR';
export const RESET = 'RESET';
export const TOGGLE_THEME = 'TOGGLE_THEME';